import type { Lang } from './types';

export const PRIVACY_URL = 'https://puppytrack.app/privacy'; // deploy sonrası güncellenecek

export const BREED_SIZES = {
  small:  { tr: 'Küçük Irk',  en: 'Small Breed',  bladderHours: 1.5 },
  medium: { tr: 'Orta Irk',   en: 'Medium Breed', bladderHours: 2.0 },
  large:  { tr: 'Büyük Irk',  en: 'Large Breed',  bladderHours: 2.5 },
  giant:  { tr: 'Dev Irk',    en: 'Giant Breed',  bladderHours: 3.0 },
} as const;

export const HOME_TYPES = {
  apartment: { tr: 'Daire',      en: 'Apartment' },
  garden:    { tr: 'Bahçeli Ev', en: 'House with Garden' },
} as const;

export const LEVELS = {
  1: { tr: 'SEVİYE 1: BAŞLANGIÇ',    en: 'LEVEL 1: BEGINNER' },
  2: { tr: 'SEVİYE 2: ÖĞRENİYOR',   en: 'LEVEL 2: LEARNING' },
  3: { tr: 'SEVİYE 3: GELİŞİYOR',   en: 'LEVEL 3: IMPROVING' },
  4: { tr: 'SEVİYE 4: USTALAŞIYOR', en: 'LEVEL 4: MASTERING' },
  5: { tr: 'SEVİYE 5: USTA',         en: 'LEVEL 5: MASTER' },
} as const;

export const DOG_AVATARS = ['🐶', '🐕', '🦮', '🐩', '🐾', '🐕‍🦺', '🐈', '🐱', '🦊', '🐻'];

export const DATA_COLORS = { pee: '#F5C547', poop: '#8B5E3C', both: '#E8520A' } as const;

type Translations = Record<string, string>;
export const T: Record<Lang, Translations> = {
  tr: {
    appName: 'PuppyTrack', today: 'Bugün ne oldu?', todayRec: 'BUGÜN', records: 'kayıt',
    success: 'BAŞARI', accident: 'KAZA', accidentStatus: 'Kaza Oldu', correctPlace: 'Doğru Yer',
    onlyPee: 'Sadece Çiş', onlyPoop: 'Sadece Kaka', both: 'İkisi Birden',
    noRecord: 'Bugün henüz bir şey girmedik! Bir kayıt ekle, köpeğinin tuvalet vaktini birlikte hesaplayalım.',
    saved: 'Başarıyla kaydedildi!', recType: 'Kayıt Türü',
    pred: 'TAHMİN',
    analysis: 'Analiz', summary: 'Özet', time: 'Zaman', trend: 'Trend', dist: 'Dağılım',
    streakTitle: 'Kazasız Seri', days: 'Gün', lastAcc: 'Son kaza: Çiş',
    hourly: 'Saatlik Kaza Dağılımı', last24: 'Son 24 Saat',
    timePeriod: 'Zaman Dilimi Analizi', night: 'Gece', morning: 'Sabah', noon: 'Öğlen', evening: 'Akşam',
    dailyDist: 'Günlük Dağılım', last7: 'Son 7 Günlük Toplam',
    accCount: 'Kaza Sayısı', accType: 'Kaza Türü Payı', detailedComp: 'Detaylı Karşılaştırma',
    pee: 'Çiş', poop: 'Kaka', bothShort: 'İkisi de',
    history: 'Geçmiş', all: 'Tümü', accidents: 'Kazalar', profile: 'Profil',
    total: 'TOPLAM', totalDays: 'GÜN', successRate: 'BAŞARI',
    goals: 'Hedefler', dailyPee: 'Günlük Başarılı Çiş', streak: 'Kazasız Gün Serisi',
    notifs: 'Bildirimler & Hatırlatıcılar', location: 'Konum Ayarları',
    exportMenu: 'Verileri Dışa Aktar (PDF)', settings: 'Uygulama Ayarları',
    home: 'GİRİŞ', statsNav: 'ANALİZ', historyNav: 'GEÇMİŞ', profileNav: 'PROFİL',
    selectType: 'Tür seç', back: 'Geri',
    insightGreat: 'Harika gidiyorsunuz! Köpeğin rutini oturtmuş görünüyor.',
    insightOk: 'İyi ilerliyorsunuz. Birkaç kazasız gün daha seriye ekleyin.',
    insightBad: 'Kazalar devam ediyor. Su sonrası 15 dk tuvalet rutini deneyin.',
    insightNoData: 'Henüz yeterli veri yok. Kayıt eklemeye devam edin.',
    morningReminder: 'Sabah Hatırlatıcısı', nightCheck: 'Gece Kontrolü', weeklyReport: 'Haftalık Rapor',
    waterLog: 'Su içti', foodLog: 'Mama yedi',
    feedingRhythm: 'Beslenme Ritmi',
    waterRhythm: 'Su sonrası çiş', foodRhythm: 'Mama sonrası kaka',
    alertIn: 'dk sonra uyarı', otherNotifs: 'Diğer Bildirimler',
    noRhythmData: 'Henüz yeterli kayıt yok — varsayılan 30 dk',
    rhythmBasis: 'Son 10 kayda göre',
    feedingLogged: 'Kaydedildi', feedingFilter: 'Beslenme',
    language: 'Dil', theme: 'Tema', dogAge: 'Köpek Yaşı', dataRetention: 'Veri Saklama',
    lightTheme: 'Açık', darkTheme: 'Koyu', weeks12: '12 Hafta',
    enableLocation: 'Konum İznini Aç', exportBtn: 'PDF İndir',
    closeToast: 'Bildirimi kapat', deleteLog: 'Kaydı sil',
    toggleOn: 'Açık', toggleOff: 'Kapalı', profileBtn: 'Profile git',
    chartAccidentDist: 'Kaza türü pasta grafiği', chartHourly: 'Saatlik kaza çubuk grafiği',
    chartDaily: 'Günlük dağılım yığılmış çubuk grafiği', chartAccCount: 'Kaza sayısı çubuk grafiği',
    progressGoal: 'ilerleme', indoor: 'İç Mekan', outdoor: 'Dış Mekan',
    addDog: 'Köpek Ekle', months: 'aylık',
    addDogTitle: 'Yeni Köpek Ekle', dogNameLabel: 'Adı', dogNamePlaceholder: 'Köpeğinin adı',
    dogAgeLabel: 'Yaşı (ay)', dogBreedLabel: 'Irk Büyüklüğü', dogHomeLabel: 'Yaşam Ortamı', dogAvatarLabel: 'Emoji',
    saveDog: 'Kaydet',
    small: 'Küçük ırk', medium: 'Orta ırk', large: 'Büyük ırk', giant: 'Dev ırk',
    apartment: 'Apartman', house: 'Bahçeli ev',
    emptyTitle: 'Henüz kayıt yok',
    emptyDesc: 'İlk kaydı ekleyerek başla. Biriktirdiğin verilerle analiz güçlenecek.',
    emptyAnalysis: 'İlk Kaydı Ekle',
    lowDataTitle: 'Analiz büyüyor', lowDataDesc: 'kayıt var. Tam grafikler için', lowDataNeeded: 'kayıt daha gerekiyor.',
    deleteConfirmTitle: 'Kaydı Sil',
    deleteConfirmDesc: 'Bu kayıt kalıcı olarak silinecek. Geri alınamaz.',
    deleteConfirmBtn: 'Evet, Sil', cancelBtn: 'İptal',
    addHistoryEntry: 'Geçmiş Kayıt Ekle',
    pickResult: 'Sonuç', pickType: 'Tür', selectDate: 'Tarih', selectTime: 'Saat', saveEntry: 'Kaydet',
    emailLabel: 'E-posta', passwordLabel: 'Şifre', loginBtn: 'Giriş Yap', signupBtn: 'Hesap Oluştur',
    loginTitle: 'Hoş Geldin', signupTitle: 'Hesap Oluştur', switchToSignup: 'Hesabın yok mu? Kayıt ol',
    switchToLogin: 'Zaten hesabın var mı? Giriş yap', logoutBtn: 'Çıkış Yap', authError: 'Hata oluştu. Tekrar dene.',
    forgotPassword: 'Şifremi unuttum', forgotTitle: 'Şifre Sıfırla', forgotDesc: 'E-posta adresini gir, sıfırlama bağlantısı gönderelim.',
    forgotBtn: 'Bağlantı Gönder', forgotSent: 'Mail gönderildi! Gelen kutunu kontrol et.', backToLogin: 'Girişe dön',
    consentTitle: 'Tüm yavrulara yardım et 🐾',
    consentBody: 'Köpeğinin anonim eğitim verileri, diğer köpeklerin daha hızlı öğrenmesine katkı sağlar. Adın, mailin veya kişisel hiçbir bilgin paylaşılmaz. Sadece "sabah 7\'de başarılı, 3 aylık, orta ırk" gibi davranış kalıpları.',
    consentYes: 'Evet, yardımcı olmak istiyorum',
    consentNo: 'Hayır, teşekkürler',
    consentBadge: 'Gizliliğin korunur',
    dataShareLabel: 'Anonim veri paylaşımı', dataShareDesc: 'Köpeğinin davranış kalıplarını paylaş, diğer yavrulara yardım et.',
    privacyPolicy: 'Gizlilik Politikası',
    rhythmLabel: 'RİTİM',
    rhythmCta: 'Tuvalet ve besin girişini birlikte yap — köpeğinin kaç dk\'da bir ihtiyacı olduğunu hesaplayalım.',
    rhythmWaterResult: (min: number) => `~${min} dk'da çişi geliyor`,
    rhythmFoodResult: (min: number) => `~${min} dk'da kakası geliyor`,
    rhythmLastCalc: 'Son hesaplanma:',
  },
  en: {
    appName: 'PuppyTrack', today: 'What happened today?', todayRec: 'TODAY', records: 'records',
    success: 'SUCCESS', accident: 'ACCIDENT', accidentStatus: 'Accident', correctPlace: 'Correct Spot',
    onlyPee: 'Just Pee', onlyPoop: 'Just Poop', both: 'Both',
    noRecord: "Nothing logged yet! Add a record and we'll predict your dog's next bathroom time.",
    saved: 'Saved successfully!', recType: 'Record Type',
    pred: 'PREDICTION',
    analysis: 'Analysis', summary: 'Summary', time: 'Time', trend: 'Trend', dist: 'Dist.',
    streakTitle: 'Accident-Free Streak', days: 'Days', lastAcc: 'Last accident: Pee',
    hourly: 'Hourly Accident Distribution', last24: 'Last 24 Hours',
    timePeriod: 'Time Period Analysis', night: 'Night', morning: 'Morning', noon: 'Noon', evening: 'Evening',
    dailyDist: 'Daily Distribution', last7: 'Last 7 Days Total',
    accCount: 'Accident Count', accType: 'Accident Type Share', detailedComp: 'Detailed Comparison',
    pee: 'Pee', poop: 'Poop', bothShort: 'Both',
    history: 'History', all: 'All', accidents: 'Accidents', profile: 'Profile',
    total: 'TOTAL', totalDays: 'DAYS', successRate: 'SUCCESS',
    goals: 'Goals', dailyPee: 'Daily Successful Pee', streak: 'Accident-Free Day Streak',
    notifs: 'Notifications & Reminders', location: 'Location Settings',
    exportMenu: 'Export Data (PDF)', settings: 'App Settings',
    home: 'HOME', statsNav: 'STATS', historyNav: 'HISTORY', profileNav: 'PROFILE',
    selectType: 'Select type', back: 'Back',
    insightGreat: 'Great progress! Your dog seems to have the routine down.',
    insightOk: 'Good progress. Keep adding to the streak.',
    insightBad: 'Accidents continuing. Try a bathroom trip 15 min after water.',
    insightNoData: 'Not enough data yet. Keep logging.',
    morningReminder: 'Morning Reminder', nightCheck: 'Night Check', weeklyReport: 'Weekly Report',
    waterLog: 'Had Water', foodLog: 'Had Food',
    feedingRhythm: 'Feeding Rhythm',
    waterRhythm: 'Pee after water', foodRhythm: 'Poop after food',
    alertIn: 'min alert', otherNotifs: 'Other Notifications',
    noRhythmData: 'Not enough data yet — using 30 min default',
    rhythmBasis: 'Based on last 10 records',
    feedingLogged: 'Logged', feedingFilter: 'Feeding',
    language: 'Language', theme: 'Theme', dogAge: 'Dog Age', dataRetention: 'Data Retention',
    lightTheme: 'Light', darkTheme: 'Dark', weeks12: '12 Weeks',
    enableLocation: 'Enable Location', exportBtn: 'Download PDF',
    closeToast: 'Close notification', deleteLog: 'Delete record',
    toggleOn: 'On', toggleOff: 'Off', profileBtn: 'Go to profile',
    chartAccidentDist: 'Accident type donut chart', chartHourly: 'Hourly accidents bar chart',
    chartDaily: 'Daily stacked bar chart', chartAccCount: 'Accident count bar chart',
    progressGoal: 'progress', indoor: 'Indoor', outdoor: 'Outdoor',
    addDog: 'Add Dog', months: 'months old',
    addDogTitle: 'Add New Dog', dogNameLabel: 'Name', dogNamePlaceholder: "Your dog's name",
    dogAgeLabel: 'Age (months)', dogBreedLabel: 'Breed Size', dogHomeLabel: 'Living Environment', dogAvatarLabel: 'Emoji',
    saveDog: 'Save',
    small: 'Small breed', medium: 'Medium breed', large: 'Large breed', giant: 'Giant breed',
    apartment: 'Apartment', house: 'House with garden',
    emptyTitle: 'No records yet',
    emptyDesc: 'Start by adding your first record. Your analysis grows stronger with every log.',
    emptyAnalysis: 'Add First Record',
    lowDataTitle: 'Analysis growing', lowDataDesc: 'records so far. Need', lowDataNeeded: 'more for full charts.',
    deleteConfirmTitle: 'Delete Record',
    deleteConfirmDesc: 'This record will be permanently deleted. This cannot be undone.',
    deleteConfirmBtn: 'Yes, Delete', cancelBtn: 'Cancel',
    addHistoryEntry: 'Add Past Record',
    pickResult: 'Result', pickType: 'Type', selectDate: 'Date', selectTime: 'Time', saveEntry: 'Save',
    emailLabel: 'Email', passwordLabel: 'Password', loginBtn: 'Log In', signupBtn: 'Create Account',
    loginTitle: 'Welcome Back', signupTitle: 'Create Account', switchToSignup: "Don't have an account? Sign up",
    switchToLogin: 'Already have an account? Log in', logoutBtn: 'Log Out', authError: 'Something went wrong. Try again.',
    forgotPassword: 'Forgot password', forgotTitle: 'Reset Password', forgotDesc: 'Enter your email and we\'ll send you a reset link.',
    forgotBtn: 'Send Link', forgotSent: 'Email sent! Check your inbox.', backToLogin: 'Back to login',
    consentTitle: 'Help all puppies learn 🐾',
    consentBody: "Your dog's anonymous training data helps other puppies learn faster. Your name, email, or any personal information is never shared — only behaviour patterns like \"success at 7am, 3 months old, medium breed\".",
    consentYes: "Yes, I'd love to help",
    consentNo: 'No thanks',
    consentBadge: 'Your privacy is protected',
    dataShareLabel: 'Anonymous data sharing', dataShareDesc: 'Share your dog\'s behaviour patterns to help other puppies learn faster.',
    privacyPolicy: 'Privacy Policy',
    rhythmLabel: 'RHYTHM',
    rhythmCta: 'Log bathroom and meals together — we\'ll calculate how often your dog needs to go.',
    rhythmWaterResult: (min: number) => `~${min} min after water`,
    rhythmFoodResult: (min: number) => `~${min} min after food`,
    rhythmLastCalc: 'Last calculated:',
  },
};
